// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMgcYMFkFzChPRCS2-whCPr1qzuBBTVRQ',
    appId: '1:759504982996:web:dca603b54dc113c62d7c41',
    messagingSenderId: '759504982996',
    projectId: 'auth-app-firebase-2af13',
    authDomain: 'auth-app-firebase-2af13.firebaseapp.com',
    storageBucket: 'auth-app-firebase-2af13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxL8Yv3P1JemEeQN4v_txj_Xo_fAJXuL8',
    appId: '1:759504982996:android:222413c91d0bb1b62d7c41',
    messagingSenderId: '759504982996',
    projectId: 'auth-app-firebase-2af13',
    storageBucket: 'auth-app-firebase-2af13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL8tu6rqXXEFFtwFCdgnxgNPBoKLSVcEU',
    appId: '1:759504982996:ios:90881ed5a41eab3f2d7c41',
    messagingSenderId: '759504982996',
    projectId: 'auth-app-firebase-2af13',
    storageBucket: 'auth-app-firebase-2af13.appspot.com',
    iosBundleId: 'com.example.authAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL8tu6rqXXEFFtwFCdgnxgNPBoKLSVcEU',
    appId: '1:759504982996:ios:90881ed5a41eab3f2d7c41',
    messagingSenderId: '759504982996',
    projectId: 'auth-app-firebase-2af13',
    storageBucket: 'auth-app-firebase-2af13.appspot.com',
    iosBundleId: 'com.example.authAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMgcYMFkFzChPRCS2-whCPr1qzuBBTVRQ',
    appId: '1:759504982996:web:49eb116ec7499aa52d7c41',
    messagingSenderId: '759504982996',
    projectId: 'auth-app-firebase-2af13',
    authDomain: 'auth-app-firebase-2af13.firebaseapp.com',
    storageBucket: 'auth-app-firebase-2af13.appspot.com',
  );
}
